spring.application.name=football-monitor

# DataSource TimescaleDB
spring.datasource.url=jdbc:postgresql://localhost:5433/football
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Google OAuth2 Config (Replace with real credentials later)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:tu-client-id-aqui}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:tu-client-secret-aqui}
spring.security.oauth2.client.registration.google.scope=profile, email

# Concurrencia con Virtual Threads (Java 21)
spring.threads.virtual.enabled=true
